"""
Replay Buffer for DQN Agent

Without a replay buffer, DQN would train on consecutive
transitions: (s1,a1,r1,s2), (s2,a2,r2,s3), (s3,a3,r3,s4), ...

these are correlated, s2 directly causes s3, which causes instability in training.
Training a NN on correlated data leads to overfitting to the most recent experience 
and forgetting older experiences (catastrophic forgetting).

The replay buffer stores a large number of past transitions and samples RANDOM mini-batches for training.
Random sampling breaks the correlation between consecutive transitions, leading to more stable training and better convergence.

Also each transition can be used for multiple gradient updates.

PPO uses a rollout buffer that is DISCARDED after each policy update, so it only trains on the most recent batch of experience.
Because PPO is on-policy, it must discard old experience that was generated by an older policy. 
DQN is off-policy, so it can learn from any past experience regardless of the policy that generated it.
"""

import random
from collections import deque
import numpy as np

class ReplayBuffer:
    """
    Circular buffer storing (state, action, reqard, next_state, done) transitions for DQN.
    When buffer is full, oldest transitions are automatically overwritten (deque with maxlen)
    """
    def __init__(self, capacity: int):
        """
        Args:
            capacity: max number of transitions to store in the buffer
            when exceeded, oldest transitions are discarded to make room for new ones
        """
        self.buffer = deque(maxlen=capacity)
        # deque with maxlen automatically drops oldest items 
        # when new items are added beyond capacity, so we don't need to manually manage indices or memory

    def push(self, state: np.ndarray, action: int, reward: float, next_state: np.ndarray, done: bool):
        """
        Store one transition in the buffer.
        Args:
            state: current state vector (numpy array)
            action: action taken (int)
            reward: reward received (float)
            next_state: next state after taking the action (numpy array)
            done: whether the episode ended after this transition (bool)
        """
        self.buffer.append((state, action, reward, next_state, done))

    def sample(self, batch_size: int):
        """
        Sample a random mini-batch of transition
        
        Args:
            batch_size: no of transitions to sample for training
            
        Returns:
            tuple of np arrays: (states, actions, rewards, next_states, dones) 
            each of shape (batch_size, ...) -> batch_size rows 
        """

        batch = random.sample(self.buffer, batch_size)
        # unique random samples gives batch_size unique transitions WITHOUT REPLACEMENT 
        
        states, actions, rewards, next_states, dones = zip(*batch)
        # unzip list of tuples into seperate arrays 

        return (np.array(states, dtype=np.float32), 
                np.array(actions, dtype=np.int64), 
                np.array(rewards, dtype=np.float32), 
                np.array(next_states, dtype=np.float32), 
                np.array(dones, dtype=np.float32)) # convert to numpy arrays for easier batch processing in training
    
    def __len__(self):
        """
        Return the current number of transitions stored in the buffer.
        (useful for checking if we have enough samples to start training)
        """
        return len(self.buffer)
    
    def is_ready(self, batch_size: int) -> bool:
        """
        Returns True when buffer has enough transitions 
        to sample a full mini-batch for training.
        Training should not begin before this is True
        """
        return len(self.buffer) >= batch_size
